### DISCUSSION TITLE
Are there styles to set the controls buttons to be dark, suitable for dark style maps and interfaces?

### DISCUSSION THREAD

**Discussion by unphased** [maplibre/maplibre-gl-js#4993] [Q&A]
See title. 

I would like to avoid hacking CSS if an official style already exists.

**Comment by neodescis** [comment]
There is nothing out of the box for this, but the MapLibre CSS is pretty simple to modify or override. I created a dark theme for a project myself.

**Comment by HarelM** [comment]
Checkout the following repo: 
https://github.com/lhapaipai/maplibre-theme
It's external, but looks good I think.

**Comment by glops** [comment]
I use the following scss code with bootstrap to invert the color of the controls. 

It's very basic but it works well.

```scss
[data-bs-theme="dark"] {
    .maplibregl-ctrl {
        filter: invert(1);
    }
}
```
