### ISSUE TITLE
Problems with CI

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#132]
I submitted pull request https://github.com/maplibre/maplibre-gl-js/pull/131 and in the first test run ```unit-test``` of the action ```CI``` failed with

```
test/unit/ui/handler/scroll_zoom.test.js .............. 1/3 31s
  ScrollZoomHandler > Zooms for single mouse wheel tick with non-magical deltaY
  not ok timeout!
    signal: SIGTERM
    expired: TAP
    stack: |
      emit (node_modules/signal-exit/index.js:77:11)
      process.listener (node_modules/signal-exit/index.js:91:7)
    test: Zooms for single mouse wheel tick with non-magical deltaY
  
  ScrollZoomHandler
  not ok timeout!
```

So this was https://github.com/maplibre/maplibre-gl-js/actions/runs/738748443.

@nyurik then asked me to add a line to the changelog, which I did and which then triggered another run of the tests which went through without any error. This second run which worked was https://github.com/maplibre/maplibre-gl-js/actions/runs/738794426.

Any idea why the test might be unreliable?

**Comment by wipfli** [comment]
@msbarry

**Comment by msbarry** [comment]
There's probably some flakiness in the tests.  I've seen it more often in the browser tests, but could be in the unit tests as well.  We might want to change the github action config so that the tests retry once in case of a failure?

**Comment by wipfli** [comment]
I have mixed feelings about rerunning the test automatically. The problem is that the action cannot distinguish between a flaky test and one which fails because it has to fail. I suggest we trigger tests manually if we want to rerun them. Like this we can spot problems with the tests faster.

Maybe we can keep this issue to keep track flaky test runs.

**Comment by wipfli** [comment]
[Here](https://github.com/maplibre/maplibre-gl-js/pull/134/checks?check_run_id=2336550500) is another false negative:

```
Run yarn install --frozen-lockfile
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.4.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/maplibre-gl-js/maplibre-gl-js/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by wipfli** [comment]
And in https://github.com/maplibre/maplibre-gl-js/runs/2339962584?check_suite_focus=true

macos-latest:

```
test/unit/source/source_cache.test.js ............. 144/147
  SourceCache reloads expiring tiles > calls reloadTile when tile expires
  not ok test unfinished
    stack: |
      Test._ade‍.r.test (test/unit/source/source_cache.test.js:1584:7)
      Parser.emit (node_modules/minipass/index.js:414:25)
      Parser.emit (node_modules/minipass/index.js:414:25)
    test: calls reloadTile when tile expires
    at:
      line: 1584
      column: 7
      file: test/unit/source/source_cache.test.js
      function: Test._ade‍.r.test
    source: |
      t.test('calls reloadTile when tile expires', (t) => {
  
  not ok child test left in queue: t.test SourceCache sets max cache size correctly
  not ok test count !== plan
    --- wanted
    +++ found
    -13
    +14
    results:
      ok: false
      count: 14
      pass: 12
      fail: 2
      bailout: false
      todo: 0
      skip: 0
      plan:
        start: 1
        end: 13
        skipAll: false
        skipReason: ''
        comment: ''
      failures:
        - ok: false
          id: 13
          time: 99.598
          name: SourceCache reloads expiring tiles
        - ok: false
          id: 14
          name: >-
            child test left in queue: t.test SourceCache sets max cache size
            correctly
          parent: ''
```

and test-browser:

```
test/browser/drag.test.js
  start server

    ✓ Listening at 10.1.0.4:9968

  start browser

    ✓ platform: linux

    ✓ browser: chrome

    ✓ version: 89.0.4389.114

  dragging
    drag to the left

      1) timeout!
1..0 # no tests found
1..0 # no tests found

      2) test count !== plan
    test/browser/zoom.test.js
      start server

        ✓ Listening at 10.1.0.4:9968
      start browser

        ✓ platform: linux

        ✓ browser: chrome

        ✓ version: 89.0.4389.114
      zooming
        double click at the center

          ✓ zoomed in by 1 zoom level

  9 passing (34s)
  2 failing

  1) test/browser/drag.test.js dragging drag to the left timeout!:
     Error: timeout!


  2) test/browser/drag.test.js test count !== plan:

      test count !== plan
      + expected - actual

      -2
      +1
      
  

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
