### ISSUE TITLE
Map Source Refresh

### ISSUE THREAD

**Issue by lawrencenika** [maplibre/maplibre-gl-js#3419]
## User Story

 As a user I can delete a geometry in one of my layers of the map source via SQL command and force the maplibre GL JS map to refresh source, so that I can immediately see the deleted geometry object disappeared from my map.

## Rationale

 - Why is this feature needed?
 currently I need to wait for my martin server to reload the source so that the deleted object disappears. I have to manually force the refresh by moving around the map.
 - What are some example use cases?
 immediate update after insertion, deletion etc.
 - Can it be done today? Is there a workaround?
I searched ChatGPT, it tells me to reset my source of the map to the old source, but that would mean I have to reset all my layers for the source too, which is troublesome.

## Impact

Better UX for all users who need smooth experience with map apps built on Maplibre

**Comment by lawrencenika** [comment]
my current code for the map is

```
<Map ...>
          <Source id={"my_function_name"} type="vector" tiles={[`${process.env.NEXT_PUBLIC_MARTIN_URL}/my_function_name/{z}/{x}/{y}?filter_param=abc`]} promoteId={"id"}>
            <Layer { ...fillLayer } />
            <Layer { ...pointLayer } />
          </Source>
</Map>
```

so that s the context for why I need to refresh my source immediately to reflect changes in my DB after a DB operation and get martin + maplibre to reflect those changes asap.

**Comment by HarelM** [comment]
Can you please post maplibre code? So that we eliminate some wrappers noise?

Also, I think the main problem is cache control for the tiles - even if you refresh the map, the browser might not fetch it.

You can set a low cache control value for the tiles I guess in the server...?

Not sure there's an easy solution to this issue...

**Comment by lawrencenika** [comment]
> Can you please post maplibre code? So that we eliminate some wrappers noise?
> 
> Also, I think the main problem is cache control for the tiles - even if you refresh the map, the browser might not fetch it.
> 
> You can set a low cache control value for the tiles I guess in the server...?
> 
> Not sure there's an easy solution to this issue...

I updated the code above, how to decrease cache control value?

**Comment by HarelM** [comment]
The code above is still using some wrapper.
cache control is a server side header, depend on the backend.

**Comment by lawrencenika** [comment]
> The code above is still using some wrapper. cache control is a server-side header, depend on the backend.

My backend is martin, I simply used martin server to run the following config.yaml

```
listen_addresses: '0.0.0.0:4001'
postgres:
  connection_string: ${NEXT_PUBLIC_DATABASE_URL}
  auto_publish: true
  functions:
    my_function_name:
      schema: public
      function: my_function_name
      minzoom: 0
      maxzoom: 30
      bounds: [-180.0, -90.0, 180.0, 90.0]
  tables: {} 
```
